### ISSUE TITLE
ioprio_set is not accessible

### ISSUE THREAD

**Issue by DavidNemeskey** [jnr/jnr-posix#100]
It is a member of `LinuxPOSIX`, but that class is `default`.

**Comment by headius** [comment]
I guess we've preferred public interfaces for these sorts of things, like exists on some of the platform-specific structs. However I don't see a good reason not to expose the platform-specific POSIX classes either.

**Comment by headius** [comment]
After talking with @enebo we think it would be best to introduce a new "Linux" interface that you can cast your POSIX instance to (when appropriate) to get access to Linux-specific methods.

I have some reservations about exposing these functions at all in jnr-posix, since they are not POSIX. Logically, it might make more sense to have a "jnr-linux" that exposes Linux-specific functions. However, that does not exist and seems like a big step to take for just a few functions.

**Comment by headius** [comment]
jnr-posix 3.0.39 has been released.

**Comment by DavidNemeskey** [comment]
Guys, thanks for the quick fix! However, there is still another piece to the puzzle: the ioprio constants in `LinuxIoPrio` are also `default`, not `public`.
