### ISSUE TITLE
WindowsByHandleFileInformation private fields

### ISSUE THREAD

**Issue by redfoos** [jnr/jnr-posix#160]
Hello! 

I'm using _WindowsLibC_ to call GetFileInformationByHandle function and everything works, but I'm a little confused by the fact that the **nFileIndexHigh**, **nFileIndexLow**, and **dwVolumeSerialNumber** fields are private in the _WindowsByHandleFileInformation_ class, even though the Microsoft documentation says that file ​​are uniquely identifiable with this values. 

Could you please explain to me the reason why these fields are private?

Thank you!

**Comment by headius** [comment]
@redfoos We usually just keep things we consider internal as private until there is an obvious need for them. Once we make them public we have to "support" them.

In this case I would guess we have left them private because this API is intended to expose native POSIX features, not Windows features. There's probably not too much harm in exposing these features in jnr-posix, but it almost feels like we should have a separate win32/win64 JNR library *designed* to expose them.

**Comment by redfoos** [comment]
@headius, thanks for the clarification
