### ISSUE TITLE
Hang while handling SIGSEGV signal

### ISSUE THREAD

**Issue by serkan-ozal** [jnr/jnr-posix#68]
Hi,

I am trying to catch and handle SIGSEGV by using jnr-posix to get thread dumps and some other informations before crash. I am using the following code sample:
``` java
POSIX posix = POSIXFactory.getPOSIX();
posix.signal(Signal.SIGSEGV, new SignalHandler() {
    @Override
    public void handle(int i) {
        System.out.println("handle: " + i);
    }
});
Unsafe unsafe = ...
unsafe.putLong(0l, 0l);
```

But when I run the code, it hangs while executing `unsafe.putLong(0l, 0l);`.
When I have debugged, as far as I see, signal is handled, `jnr.ffi.provider.jffi.NativeClosureFactory$ClosureReference` is created with correct referent which contains my handler as wrapped but then `closureReference.get()` always returns null inside `NativeClosureProxy::getCallable()` so seems that there is an infinite loop because of this.

My operating system is **MacOSX** and using JDK **1.8.0_60**.
jnr-posix version is **3.0.23**.

Thanks in advance.

Regards.

**Comment by headius** [comment]
I'd be very surprised if you could get SEGV to trap, because my understanding is that most JVMs use that signal to trigger various internal events...the memory subsystem/GC knowing when to expand the heap, for example. Seems like trapping it yourself would cause all sorts of nasty issues.

The biggest example I could find is in (JDK 8 source) hotspot/src/os_cpu/linux_x86/vm/os_linux_x86.cpp, in the JVM_handle_linux_signal function. It has numerous checks for SEGV that do various things with stack and memory pages.

It might be possible to handle SEGV if you capture the previous registered function and call it, but you'd have to be pretty careful to not cause another one in yours.

**Comment by serkan-ozal** [comment]
Hi @headius 

Thanks for your response.

So you mean that it is not possible handling SIGSEGV with jnr-posix?
In fact, I will let the system crash after handler but I just want to log some information that might be helpful to find the bug on our CI environment.

**Comment by headius** [comment]
Well, I'm saying it *may* not be possible, going by what I know of the JVM. This is pretty deep magic, though, so I can't be certain.

**Comment by serkan-ozal** [comment]
Ok, I see,

In addition, do you have any idea why `jnr.ffi.provider.jffi.NativeClosureFactory$ClosureReference` is created with correct referent which contains my handler as wrapped but then `closureReference.get()` always returns null inside `NativeClosureProxy::getCallable()`?

**Comment by headius** [comment]
There's a jnr/jnr-ffi bug for issues with NativeClosureFactory...perhaps that's related?

In any case that isn't related to your SEGV trapping. Is there anything actionable here or can I close it?

**Comment by serkan-ozal** [comment]
Hi @headius 
Thanks for your response.
Yes, I think, this issue can be closed.

**Comment by serkan-ozal** [comment]
Can you also point the related issues with `NativeClosureFactory`?

**Comment by headius** [comment]
I don't recall what issue I was thinking of, but there have been several fixes to jnr-ffi that might help you. If you're still having trouble, open a new issue (perhaps with jnr-ffi instead).

Closing this one.
